### ISSUE TITLE
Separate categories of income and expenses

### ISSUE THREAD

**Issue by hieu-van** [mtotschnig/MyExpenses#451] opened 2018-02-19 10:50 UTC
Is it a good idea? I'd love to have it implemented. The categories are not separated for income and expenses, which make it hard to effectively manage cash flow.

**Comment by DSIW** [comment] 2018-02-19 10:57
The sign of amount can be used to recognize it. If the amount is positive, the transaction is income. If the amount is negative, the transaction is expense.

**Comment by mtotschnig** [comment] 2018-02-19 13:42
@hieu-van I am closing this, since its is a duplicate of #212 . But would you mind explaining how it helps managing cash flow?

**Closed by mtotschnig** 2018-02-19 13:42 UTC
