### ISSUE TITLE
Distribution chart for all accounts 

### ISSUE THREAD

**Issue by gdixith** [mtotschnig/MyExpenses#661] opened 2020-06-06 01:45 UTC
currently in distribution chart only one account is taken

some expenses are made through cash and bank both, 
to get full view we need distribution chart across multiple accounts

**Comment by mtotschnig** [comment] 2020-06-06 04:50
Duplicate of #594 
It is already possible to view distribution across aggregate (currency) accounts and the grand total accounts.
What is is not possible, is to select a subset.

**Closed by mtotschnig** 2020-06-06 04:50 UTC
