### ISSUE TITLE
Wrong calculus when moving between accounts with different money types

### ISSUE THREAD

**Issue by lupa18** [mtotschnig/MyExpenses#324] opened 2016-12-05 17:59 UTC
I made a movement from one account to another, i.e., from A (paraguayan guaraní) to B (dollars). 
Something in equation is wrong since the auto-completion of money price isn't correct. 

In the picture, I completed 10,123,500 PYG (A) and 1750 $ (B) and money price (automatic calculus) appears as 5,882.352 .. and it's wrong, must be: 5,784.86

On the other side, if I complete only first number (A) and money price (correct one), then .. automatic result of the amount in $ (B) also has wrong result. 

![2016-12-05-133600](https://cloud.githubusercontent.com/assets/463429/20896168/36eade84-bafb-11e6-8a31-b4026a9be2bd.jpg)

**Comment by mtotschnig** [comment] 2016-12-20 14:33
Many thanks for the report and sorry for the late reaction. I was able to reproduce the problem and am investigating it. Should be fixed for next release.

**Comment by mtotschnig** [comment] 2016-12-20 15:45
I am wondering if you would be willing to also provide an example for the second scenario you describe. Because if I enter first 10123500 as Importe (PYG) and then 0.00017 as exchange rate I get  Importe ($) as 1721 which seems to be correct (rounded from 1720.99500).

**Comment by lupa18** [comment] 2016-12-23 16:49
I try to repeat second scenario: problem is:
1. I fill the original value (A) 
2. then I modified rate exchange, 
3. and then, MyExpenses automatically modifies A again, instead changing B value

**Comment by mtotschnig** [comment] 2016-12-23 17:56
In step 2 which exchange rate do you enter, 1 PYG = _ $, or 1 $ = _ PYG. If you enter the first one, B value should change, if you enter the second one, A value should change.
This is how it is currently designed: that the amount for the currency for which you enter the variable amount is calculated. This might not be completely intuitive, but I do not know currently how to improve it.

**Comment by lupa18** [comment] 2016-12-23 20:24
Ok, from my point of view, A value doesn't have to change, since is the "from" account I want to move (I mean, I got some PYG and went to exchange market to get $). Then, 1$ = _ PYG is the intuitive value we use when exchanging money to and from dollar. 
From my perspective, when you modify the exchange rates (any of them), B is the only value that has to be automatic modified, because it depends on rates I got in the market.

**Comment by mtotschnig** [comment] 2016-12-23 20:35
I understand that when you have a fixed amount of PYG that you want to transfer, you might want to use either of the two exchange rates. But what if the amount that should land on the To account is fixed, say you need to transfer that much money from the PYG, that 1000 $ arrive at the other hand? Maybe the solution would be some kind of handle that would allow the user to indicate which side should be fixed, and which calcualted?

**Comment by lupa18** [comment] 2016-12-24 00:36
maybe the first that I complete sholud be fixed ?

**Comment by mtotschnig** [comment] 2016-12-24 11:48
That is an excellent suggestion, thanks. Will try to implement that.

**Comment by mtotschnig** [comment] 2017-03-06 07:05
Current implementation introduces new problem, as reported by user:
If I'm filling in the transfer amounts for both from and to the app will no longer allow me to do that. It always calculates the to amount based on the prior transaction. When I manually correct the to field it will change the amount of the from field.  There's no way around this. Hence there's no longer an easy way to do transfers with accurate amounts.

**Closed** 2017-03-07 00:42 UTC
Labels: next_release
