### ISSUE TITLE
Balance on a particular date for a particular account

### ISSUE THREAD

**Issue by anishmittal2020** [mtotschnig/MyExpenses#954] opened 2022-04-08 08:13 UTC
How can we find out the closing balance on a particular date for a particular account? Is it possible, to show when we click any particular entry?

In my N26 Banking App, the closing balance is shown at the very top for the transaction date at the top most visible row as one scrolls through the entries.

**Comment by mtotschnig** [comment] 2022-04-09 16:53
Please correct me if I am wrong: This seems to be a duplicate of #239 .

**Comment by anishmittal2020** [comment] 2022-04-09 22:06
@mtotschnig You are right. I solved this problem by grouping by day as shown below:

![image](https://user-images.githubusercontent.com/42092626/162593049-2dae0f40-78c9-4450-bd5f-2cffc6126dbf.png)

**Comment by mtotschnig** [comment] 2022-04-10 02:17
@anishmittal2020  Yes, thanks for clarifying that balance per day is already provided by the grouping feature. #239 is about balance for every transaction.

**Closed by mtotschnig** 2022-04-10 02:17 UTC
