### ISSUE TITLE
Creation in double

### ISSUE THREAD

**Issue by lauco74** [mtotschnig/MyExpenses#248] opened 2015-09-23 23:04 UTC
Lors d'une importation d'un fichier qif, les catégories et sous-catégories sont recréées en double bien qu'elles existaient déja auparavant
When importing a file qif, the categories and subcategories are recreated in double although they existed already before.

**Comment by mtotschnig** [comment] 2015-09-24 21:34
Could you send me an example file where this happens?

**Comment by mtotschnig** [comment] 2015-09-26 12:23
The reported issue was caused by whitespace not being trimmed from category labels. This has been fixed with 6c5701934602d3f6a52543104ec047f43d94a92c

**Closed by mtotschnig** 2015-09-26 12:23 UTC
