### ISSUE TITLE
Ability to add user-defined currencies

### ISSUE THREAD

**Issue by hieu-van** [mtotschnig/MyExpenses#475] opened 2018-04-14 07:57 UTC
Hi Michael,
I know this feature is perhaps not so important but for example, in Asia, some countries use different measurement for precious metals (e.g. Tael). Would consider implementing it?

**Comment by mtotschnig** [comment] 2018-04-15 08:29
Thanks you for the suggestion. This is definitely something on the roadmap, since it is essentially a more generalized, and hence more useful version of #390 .

**Comment by mtotschnig** [comment] 2018-06-23 15:47
Duplicate of #264

**Closed by mtotschnig** 2018-06-23 15:47 UTC
