### ISSUE TITLE
Support sub sub categories (multiple nested levels)

### ISSUE THREAD

**Issue by ypid** [mtotschnig/MyExpenses#596] opened 2019-10-20 18:09 UTC
Hi,

Applications like GnuCash or KMyMoney can have as many nesting levels of categories as you like. What is the reason to limit it to categories and subcategories only?

**Comment by mtotschnig** [comment] 2019-11-18 21:39
Duplicate of #156 
I think originally the reason was implementation complexity and the fact that Grisbi (for which My Expenses was designed as a companion) also had only two levels.

**Closed by mtotschnig** 2019-11-18 21:39 UTC
