### ISSUE TITLE
Option to save accounts to SD card by default

### ISSUE THREAD

**Issue by WallGeckoPoint** [mtotschnig/MyExpenses#537] opened 2018-12-09 10:19 UTC
Feature request: make the directory where accounts are saved user-changeable, so that we can e.g save accounts to the SD card by default.

Example use cases:
- when a device is shared across multiple people (common in some countries)
- in preparation for changing to a new device (there's an enormous temptation to add new transactions once a backup has been made, especially if setting up the new device takes longer than expected)
- when the device itself is not reliable but no new device is immediately available (e.g if the device  starts failing while the user is travelling)

**Comment by mtotschnig** [comment] 2019-01-17 15:20
I suppose you mean storage of the database, then this is duplicate of #482 . Please reopen if I misunderstood and you have something different in mind.

**Closed by mtotschnig** 2019-01-17 15:20 UTC
