### ISSUE TITLE
[feature request] More categories per entry / tag system

### ISSUE THREAD

**Issue by funnym0nk3y** [mtotschnig/MyExpenses#520] opened 2018-10-04 13:57 UTC
Recently a had the wish to tag a entry with more than one category. For example if I buy a tool to fix my car, it is an expense related and caused by my car, but also something for my workshop. In my opinion this would improve the analytical capabilities of the app. Therefore I suggest a system which either can assign two or more categories to one entry, or something like a tag system, where statistics can be shown for several tags independently.

**Comment by mtotschnig** [comment] 2018-10-05 21:06
duplicate of #142

**Closed by mtotschnig** 2018-10-05 21:06 UTC
