### ISSUE TITLE
Manual groups

### ISSUE THREAD

**Issue by sedrubal** [mtotschnig/MyExpenses#994] opened 2022-06-10 08:49 UTC
We need to group transactions manually as we check our cashbox irregularly. So we need a feature like it already exists for grouping transactions by day, week, month, year. Is it possible to implement grouping by a tag for example?

**Comment by mtotschnig** [comment] 2022-07-21 14:05
Duplicate of #582

**Closed by mtotschnig** 2022-07-21 14:05 UTC
