### ISSUE TITLE
Suggestions for notes

### ISSUE THREAD

**Issue by contrapunctus-1** [mtotschnig/MyExpenses#535] opened 2018-12-07 20:01 UTC
A feature which would make my workflow with this app a whole lot better is to have suggestions ('completion'?) for notes, similar to what exists for Payee/Payer, and ideally sensitive to the Payee/Payer entered i.e. for party A, only suggest notes which I have used with party A in the past.

**Comment by mtotschnig** [comment] 2020-12-24 12:14
Duplicate of #446

**Closed by mtotschnig** 2020-12-24 12:14 UTC
