### ISSUE TITLE
Linebreak in notes

### ISSUE THREAD

**Issue by yashpalgoyal1304** [mtotschnig/MyExpenses#957] opened 2022-04-17 11:48 UTC
The notes text field should support taking linebreak as input. Currently it shows a checkmark in keyboard on android 11 on myexpenses : 3.3.7 (515)

**Comment by mtotschnig** [comment] 2022-04-19 07:01
Duplicate of #714 , which I will add to the Roadmap Vote.

**Closed by mtotschnig** 2022-04-19 07:01 UTC
