### ISSUE TITLE
Compact view of accounts

### ISSUE THREAD

**Issue by hieu-van** [mtotschnig/MyExpenses#490] opened 2018-06-23 15:36 UTC
I'm thinking of a more compact view of accounts, which shows just the net balance of each one, instead of their opening balance, so and so. Is it good enough to be implemented?

**Comment by mtotschnig** [comment] 2018-06-23 15:49
Duplicate of #397 . Please add your comments there.

**Closed by mtotschnig** 2018-06-23 15:49 UTC
