### ISSUE TITLE
Cosmetic: Transactions dates are shown in US format

### ISSUE THREAD

**Issue by sabi0** [mtotschnig/MyExpenses#607] opened 2020-01-16 10:53 UTC
When transactions grouping is disabled the dates are shown as '1/16/20'.
To avoid the confusion between month and date I'd suggest to use an abbreviated month name: 'Jan 16, 2020'

I suppose the date format follows primary system language selection. I have English (US).
I do prefer to keep my phone language like that. And would like to have non-ambiguous dates display.

**Comment by sabi0** [comment] 2020-01-16 11:34
This also applies to other places like "This week (1/13 - 1/19 )".
Though it is less confusing there.

**Comment by mtotschnig** [comment] 2020-01-27 15:49
Did you consider using English (UK) as system language, which would give you the European date format?

**Comment by sabi0** [comment] 2020-01-27 16:17
That's a good tip. Thank you. I could bear with "colour" and "favourite".
(I tried doing that in the past. But I guess I changed the keyboard language instead of system locale.)

However I still find dates like '06/01' more difficult to grasp. And would prefer textual months names: 'Jan 6'

**Comment by mtotschnig** [comment] 2020-05-09 18:15
Duplicate of #333

**Closed by mtotschnig** 2020-05-09 18:15 UTC
