### ISSUE TITLE
add current balance to every expense value

### ISSUE THREAD

**Issue by mjechow** [mtotschnig/MyExpenses#1003] opened 2022-07-22 13:18 UTC
I suggest following addidtion:

I would like to see a second value (small and under the actual expense value) for every entry that shows the balace of the account at the time of the expense. Like financisto is doing it. That information helps a lot during manual synchronisation between bank account and MyExpenses, because you see very fast at with time both where in synch and when there has to be a missing expense.

Thank you for your fantastic work, I switched from financisto Moments ago.

**Comment by mtotschnig** [comment] 2022-07-23 10:05
Duplicate of #239 . You can add your vote to it via the Vote on the Roadmap from the app's settings.

**Closed by mtotschnig** 2022-07-23 10:05 UTC

**Comment by mjechow** [comment] 2022-07-23 10:18
I was looking carefully, but oversaw it. Thanks!
