### ISSUE TITLE
Cumulative budgets

### ISSUE THREAD

**Issue by bootywizard002** [mtotschnig/MyExpenses#948] opened 2022-04-03 06:32 UTC
Can we have cumulative budgets? 

I want to be able to budget my expenses, for example, food, in a daily manner without exceeding a daily average while being able to spend a little more occasionally (eating out with friends). I know I can set a monthly budget and try managing it monthly but that's a bit complicated and harder to keep track of. 

I don't think that implementing this feature is complicated and if you guys have time to implement it, it would mean a lot to me.

**Comment by mtotschnig** [comment] 2022-04-03 09:39
@bootywizard002 This seems a duplicate of #915 . Please reopen if you disagree.

**Closed by mtotschnig** 2022-04-03 09:39 UTC
