### ISSUE TITLE
Cycle date

### ISSUE THREAD

**Issue by MauricioSheva** [mtotschnig/MyExpenses#1303] opened 2023-11-13 04:57 UTC
Can we set a different cycle date for each credit card account?

As far as I know, we can only filter by day, month or year, but we lack a filter by cycle date, which could be different for each account.

This will help to have "bank statements'" for each account whenever we filter by cycle date.

Thanks! Keep up the good work!

**Comment by mtotschnig** [comment] 2023-11-13 07:28
@MauricioSheva Thank you for the suggestion. I suppose you are referring to the Grouping feature. Could you give an example of such a cycle? You already can configure the start of week and the start of month, and there is a ticket for configuring start of year: #318

**Comment by MauricioSheva** [comment] 2023-11-13 08:05
Yes, it could be set through the Grouping feature but my suggestion is more related to whenever you create/edit an account. The cycle date should be aligned with the bank closing date of the credit card, to have periods equals to those of the actual account. This closing/cycle date is different for every account, so the cycle for an account with day 20 as his closing/cycle date, will go from the 21st of a month till the 20th of the following month and so on.
This will save time because you'll define the period for every account since the creation of an account instead of using and setting the filters every time through the Grouping feature.
Thanks!

**Comment by mtotschnig** [comment] 2023-11-13 08:19
So, if I understand you correctly, you would like to be able to configure the start of the grouping period per account, instead of setting it globally.

**Comment by mtotschnig** [comment] 2023-11-13 08:26
In which case, this is a duplicate of #545

**Comment by MauricioSheva** [comment] 2023-11-13 12:37
Yes, I would like to configure the start of the Grouping period per account. Seems the issue is a duplicate and it's on the to-do list.
Thank you!

**Comment by mtotschnig** [comment] 2023-11-14 04:53
As discussed, closing this as duplicate.

**Closed by mtotschnig** 2023-11-14 04:53 UTC
