### ISSUE TITLE
Improve the transactions list by offering a different layout

### ISSUE THREAD

**Issue by OmarNamis** [mtotschnig/MyExpenses#966] opened 2022-05-01 10:24 UTC
The current layout for transactions list feels a bit too compact for me, which makes it harder to distinguish each transaction, as well as tell where each item is (category, payee, notes, etc.).

It'd be great if there was an option for a more cozy layout with some spacing between each transaction, and multilines where each item for the transaction is locked in place.

Something that looks like this from the [bluecoins](https://play.google.com/store/apps/details?id=com.rammigsoftware.bluecoins) app:
![Screenshot_20220501-115247~(1).jpg](https://user-images.githubusercontent.com/14346945/166141765-9c05817a-33c7-44cf-aee4-b9c4d61b14d7.jpg)

And also it would be really cool if the category icon was visible in the list in a similar way to the screenshot.

**Comment by mtotschnig** [comment] 2022-05-02 09:13
@OmarNamis Thank you for the input. This is something to take up hopefully shortly. Duplicate of #546 .

**Closed by mtotschnig** 2022-05-02 09:13 UTC

**Comment by mtotschnig** [comment] 2023-04-22 07:36
@OmarNamis If you are still listening, I'd be interested to learn if the new design of the app is in line with what you had in mind when you created this ticket?

**Comment by OmarNamis** [comment] 2023-04-25 04:51
Hi @mtotschnig !
Yes, I have been following the recent changes and the new design looks a lot better and much more easier to read.

There could be some room for improvement though, like if it was possible to select specific elements to hide it or even reorder the elements as the user prefers.

Thank you for your efforts!

**Comment by mtotschnig** [comment] 2023-08-25 13:03
@OmarNamis Thanks for the feedback. Configuring the order of presentation is tracked at #1217
